from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
BACKUP_DIR = PROJECT_ROOT / "backups"

DATABASE_PATH = DATA_DIR / "liga_mx.db"
SINGLE_USER_PREDICTOR = "Hiram"

DEFAULT_ELO = 1500.0
HOME_ADVANTAGE_ELO = 65.0
ELO_K_FACTOR = 30.0

ELO_HOME_ADVANTAGE = 80.0

MAX_DRAW_PROBABILITY = 0.28
MIN_DRAW_PROBABILITY = 0.12
DRAW_DECAY_SCALE = 400.0

POISSON_DEFAULT_HOME_GOALS = 1.4
POISSON_DEFAULT_AWAY_GOALS = 1.1
POISSON_PRIOR_MATCHES = 5.0
POISSON_MAX_GOALS = 10
